package com.example.Cat.s.Blog.ui;

import com.vaadin.flow.spring.security.AuthenticationContext;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

@Component
public class SecurityService {

    private final AuthenticationContext authenticationContext;

    public SecurityService(AuthenticationContext authenticationContext) {
        this.authenticationContext = authenticationContext;
    }

    /**
     * There was an exception while trying to navigate to 'home' with the root cause 'java.util.NoSuchElementException: No value present'
     * org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.Cat.s.Blog.ui.MainLayout': Failed to instantiate [com.example.Cat.s.Blog.ui.MainLayout]: Constructor threw exception
     * at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:321)
     * at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:309)
     * at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
     * at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
     * at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
     * at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
     * at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:320)
     * at com.vaadin.flow.spring.SpringInstantiator.getOrCreate(SpringInstantiator.java:126)
     * at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:136)
     * at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:132)
     * at java.base/java.util.Optional.orElseGet(Optional.java:364)
     * at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:131)
     * at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:480)
     * at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:461)
     * at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:211)
     * at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78)
     * at com.vaadin.flow.component.UI.handleNavigation(UI.java:1853)
     * at com.vaadin.flow.component.UI.renderViewForRoute(UI.java:1816)
     * at com.vaadin.flow.component.UI.connectClient(UI.java:1729)
     * at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     * at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
     * at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     * at java.base/java.lang.reflect.Method.invoke(Method.java:568)
     * at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:227)
     * at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:204)
     * at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:150)
     * at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:133)
     * at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74)
     * at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:466)
     * at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$4(ServerRpcHandler.java:447)
     * at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
     * at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:447)
     * at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:324)
     * at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114)
     * at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
     * at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1573)
     * at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398)
     * at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106)
     * at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
     * at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
     * at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
     * at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:642)
     * at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:408)
     * at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:313)
     * at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:277)
     * at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141)
     * at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:178)
     * at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)
     * at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
     * at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
     * at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
     * at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
     * at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
     * at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
     * at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
     * at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
     * at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
     * at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
     * at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
     * at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
     * at com.example.Cat.s.Blog.filter.JwtAuthenticationFilter.doFilterInternal(JwtAuthenticationFilter.java:40)
     * at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     * at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
     * at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
     * at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
     * at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
     * at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
     * at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
     * at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
     * at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
     * at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
     * at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
     * at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
     * at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
     * at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     * at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     * at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
     * at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
     * at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
     * at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
     * at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
     * at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
     * at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
     * at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     * at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
     * at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
     * at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
     * at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     * at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
     * at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
     * at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
     * at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     * at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
     * at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
     * at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
     * at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
     * at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
     * at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
     * at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
     * at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
     * at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
     * at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
     * at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
     * at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
     * at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
     * at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
     * at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
     * at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
     * at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     * at java.base/java.lang.Thread.run(Thread.java:833)
     * Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.Cat.s.Blog.ui.MainLayout]: Constructor threw exception
     * at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
     * at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110)
     * at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:318)
     * ... 132 more
     * Caused by: java.util.NoSuchElementException: No value present
     * at java.base/java.util.Optional.get(Optional.java:143)
     * at com.example.Cat.s.Blog.ui.SecurityService.getAuthenticatedUser(SecurityService.java:17)
     * at com.example.Cat.s.Blog.ui.MainLayout.createHeader(MainLayout.java:38)
     * at com.example.Cat.s.Blog.ui.MainLayout.<init>(MainLayout.java:18)
     * at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     * at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
     * at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     * at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
     * at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
     * at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
     * ... 134 more
     *
     * @return
     */
    public UserDetails getAuthenticatedUser() {
        return authenticationContext.getAuthenticatedUser(UserDetails.class).get(); //
    }


    public void logout() {
        authenticationContext.logout();
    }
}